const FAQS = [
  {
    q: "Which programmes does the assistant cover?",
    a: "CHARUSAT's four online degree programmes — BBA, BCA, MBA and MCA — including their admission data, programme regulations (PPRs) and related policies such as the fees refund policy.",
  },
  {
    q: "Where do the answers come from?",
    a: "Answers are generated by retrieving relevant passages from official CHARUSAT knowledge-base documents (programme regulations, fee schedules and policies) and answering strictly from them. If sources disagree, the assistant flags the conflict instead of guessing.",
  },
  {
    q: "Is this an official admissions channel?",
    a: "No. The assistant is an informational tool. Always verify details with official CHARUSAT channels before making admission or payment decisions.",
  },
  {
    q: "Do I need an account to use it?",
    a: "No. Open the page and start asking — no sign-up required.",
  },
];

export default function Faq() {
  return (
    <section id="faq" className="mx-auto max-w-3xl scroll-mt-24 px-4 py-24 sm:px-6">
      <div className="text-center">
        <p className="text-sm font-semibold tracking-wider text-indigo-600 uppercase">FAQ</p>
        <h2 className="font-display mt-2 text-3xl font-bold tracking-tight text-slate-900 sm:text-4xl">
          Frequently asked questions
        </h2>
      </div>

      <div className="mt-10 divide-y divide-slate-200 rounded-2xl border border-slate-200 bg-white shadow-sm">
        {FAQS.map((f) => (
          <details key={f.q} className="group px-6 py-5">
            <summary className="flex cursor-pointer list-none items-center justify-between gap-4 text-left text-[15px] font-semibold text-slate-900 [&::-webkit-details-marker]:hidden">
              {f.q}
              <svg
                viewBox="0 0 24 24"
                className="h-5 w-5 shrink-0 fill-none stroke-slate-400 stroke-2 transition-transform duration-200 group-open:rotate-45"
              >
                <path d="M12 5v14M5 12h14" />
              </svg>
            </summary>
            <p className="mt-3 text-sm leading-relaxed text-slate-600">{f.a}</p>
          </details>
        ))}
      </div>
    </section>
  );
}
