"""LLM client using the modern ``google.genai`` SDK.

Responsibilities
----------------
* discover candidate Gemini models and keep a working list;
* generate answers with retries and exponential backoff;
* classify failures into typed errors so callers can distinguish a
  retrieval problem from an LLM problem, an API quota limit, a timeout or
  any other API error;
* produce a deterministic, structured local answer from the retrieved
  evidence when the API is unavailable (no key, quota exhausted, timeout,
  model retired, ...) so the chatbot always answers something useful.

The local fallback never performs arithmetic the source document does not
state, and it never dumps raw chunk text: it extracts concrete claims using
the same configurable taxonomy as conflict detection (see ``app.conflict``).
"""
from __future__ import annotations

import re
import time
from typing import Dict, List, Optional, Tuple

from google import genai
from google.genai import types as genai_types

try:
    from groq import Groq
    HAS_GROQ = True
except ImportError:
    Groq = None
    HAS_GROQ = False

from app import config
from app.conflict import extract_claims, focus_attributes, format_conflict_notice
from app.utils import logger, print_info, print_warning

NOT_FOUND_ANSWER = "I couldn't find this information in the university knowledge base."


class LLMStatus:
    """Generation status returned alongside every answer."""

    LLM = "gemini"                   # answer generated by the Gemini API
    GEMINI = "gemini"                # alias for Gemini answer
    GROQ = "groq"                    # answer generated by Groq fallback tier
    FALLBACK = "fallback"         # deterministic local generation (no key/model)
    QUOTA = "quota"               # API quota exhausted -> local fallback used
    TIMEOUT = "timeout"           # request timed out -> local fallback used
    GENERATION_ERROR = "generation_error"  # empty/invalid model output -> fallback used
    API_ERROR = "api_error"       # any other API failure -> fallback used
    EMPTY = "empty"               # no evidence found at all


class RetrievalError(RuntimeError):
    """Raised when evidence cannot be retrieved from the knowledge base."""


class LLMGenerationError(RuntimeError):
    """Base error for LLM generation failures."""


class APIQuotaError(LLMGenerationError):
    """API quota/rate limit exceeded (HTTP 429, RESOURCE_EXHAUSTED)."""


class LLMTimeoutError(LLMGenerationError):
    """Generation request timed out."""


class APIAccessError(LLMGenerationError):
    """Any other API access failure (auth, unavailable model, 5xx, ...)."""

    def __init__(self, message: str, *, unavailable: bool = False) -> None:
        super().__init__(message)
        self.unavailable = unavailable


class LLMClient:
    """Generates answers with Gemini models, Groq fallback tier, and deterministic local fallback."""

    def __init__(self) -> None:
        self.api_key = config.get_api_key()
        self.groq_api_key = config.get_groq_api_key()
        self._client: Optional[genai.Client] = None
        self._groq_client: Optional[Groq] = None
        self._gen_config = None
        self._working_models: List[str] = []
        self._quota_exhausted = False
        self._cooldown_until = 0.0
        self._last_status = LLMStatus.FALLBACK
        self._initialize()

    # ------------------------------------------------------------------
    # Initialisation
    # ------------------------------------------------------------------

    def _initialize(self) -> None:
        if self.groq_api_key and HAS_GROQ:
            try:
                self._groq_client = Groq(api_key=self.groq_api_key)
                print_info(f"Groq client initialised for fallback tier (model: {config.GROQ_MODEL}).")
            except Exception as exc:
                logger.error("Failed to initialise Groq client: %s", exc)
                self._groq_client = None

        if not self.api_key:
            print_warning("[WARNING] GOOGLE_API_KEY is missing or invalid in .env file.")
            if self._groq_client:
                print_info("Groq fallback tier will be used primary.")
            else:
                print_warning("Using local fallback answer generation from retrieved context.")
            logger.warning("GOOGLE_API_KEY missing; fallback tier active")
            return

        try:
            self._client = genai.Client(
                api_key=self.api_key,
                http_options=genai_types.HttpOptions(
                    timeout=int(config.LLM_TIMEOUT),
                    retryOptions=genai_types.HttpRetryOptions(attempts=1),
                ),
            )
            self._gen_config = genai_types.GenerateContentConfig(
                temperature=config.LLM_TEMPERATURE,
                max_output_tokens=1024,
            )
        except Exception as exc:
            logger.error("Failed to initialise Gemini client: %s", exc)
            self._client = None
            return

        discovered = self._discover_models()
        self._working_models = discovered or list(config.PREFERRED_MODELS)
        if self._working_models:
            print_info(f"Gemini client ready; candidate models: {', '.join(self._working_models)}")
        else:
            print_warning("[WARNING] No Gemini models available; using local fallback.")

    def _discover_models(self) -> List[str]:
        """Return available Gemini model names in preferred order.

        Some models are still *listed* but reject generation for new users
        (404); those are removed lazily when a call fails, so discovery never
        burns quota probing generation.
        """
        try:
            available = set()
            for model in self._client.models.list():
                name = getattr(model, "name", "")
                actions = getattr(model, "supported_actions", None) or []
                if name and "generateContent" in actions:
                    available.add(name)
            logger.info("Available Gemini models (generateContent): %s", sorted(available))

            preferred = [name for name in config.PREFERRED_MODELS if name in available]
            others = sorted(name for name in available if "gemini" in name)
            return preferred + [name for name in others if name not in preferred]
        except Exception as exc:
            logger.error("Model discovery failed: %s", exc)
            return []

    # ------------------------------------------------------------------
    # Generation
    # Fallback Chain: Gemini (multi-model) -> Groq -> raw chunk fallback
    # ------------------------------------------------------------------

    def generate(
        self,
        prompt: str,
        *,
        context_chunks: Optional[List[Tuple[str, Dict[str, object]]]] = None,
        conflicts: Optional[List[Dict[str, object]]] = None,
    ) -> Tuple[str, str]:
        """Generate an answer using the fallback chain: Gemini -> Groq -> Local.

        Returns ``(text, status)`` where status is one of ``LLMStatus``.
        """
        if not (self.api_key and self._client and self._working_models):
            groq_text = self._try_groq(prompt)
            if groq_text:
                self._last_status = LLMStatus.GROQ
                return groq_text, LLMStatus.GROQ
            return self._fallback_generate(prompt, context_chunks, conflicts), LLMStatus.FALLBACK

        if self._quota_exhausted:
            logger.warning("Gemini quota exhausted; attempting Groq fallback")
            groq_text = self._try_groq(prompt)
            if groq_text:
                self._last_status = LLMStatus.GROQ
                return groq_text, LLMStatus.GROQ
            return self._fallback_generate(prompt, context_chunks, conflicts), LLMStatus.QUOTA

        if time.time() < self._cooldown_until:
            logger.info(
                "Gemini API in cooldown (%.0fs left); attempting Groq fallback",
                self._cooldown_until - time.time(),
            )
            groq_text = self._try_groq(prompt)
            if groq_text:
                self._last_status = LLMStatus.GROQ
                return groq_text, LLMStatus.GROQ
            return self._fallback_generate(prompt, context_chunks, conflicts), self._last_status

        last_error: Optional[Exception] = None
        seen_quota = False
        seen_timeout = False
        for model in list(self._working_models):
            try:
                text = self._generate_once(model, prompt)
                self._last_status = LLMStatus.GEMINI
                return text, LLMStatus.GEMINI
            except (APIQuotaError, LLMTimeoutError, APIAccessError, LLMGenerationError) as exc:
                last_error = exc
                if isinstance(exc, APIQuotaError):
                    seen_quota = True
                elif isinstance(exc, LLMTimeoutError):
                    seen_timeout = True
                logger.warning("%s with model %s: %s", type(exc).__name__, model, exc)
                if isinstance(exc, APIAccessError) and exc.unavailable:
                    self._working_models.remove(model)
                    logger.info("Removed unavailable model %s from working set", model)
                continue

        if seen_quota:
            self._quota_exhausted = True
            status = LLMStatus.QUOTA
        elif seen_timeout:
            status = LLMStatus.TIMEOUT
        else:
            status = self._status_for(last_error)
        self._last_status = status
        self._cooldown_until = time.time() + config.LLM_COOLDOWN_SECONDS
        logger.warning("All Gemini models failed (%s); attempting Groq fallback tier", status)

        groq_text = self._try_groq(prompt)
        if groq_text:
            logger.info("Groq fallback generation succeeded")
            self._last_status = LLMStatus.GROQ
            return groq_text, LLMStatus.GROQ

        logger.warning("Groq fallback unavailable or failed; using local raw chunk fallback")
        return self._fallback_generate(prompt, context_chunks, conflicts), status

    def _try_groq(self, prompt: str) -> Optional[str]:
        """Attempt answer generation using Groq API as a fallback tier.

        Reuses the exact same prompt/context that was sent to Gemini.
        Wrapped in try/except with a short timeout (5-10s).
        """
        if not self._groq_client:
            if not self.groq_api_key or not HAS_GROQ:
                return None
            try:
                self._groq_client = Groq(api_key=self.groq_api_key)
            except Exception as exc:
                logger.error("Failed to initialise Groq client: %s", exc)
                return None

        try:
            logger.info("Calling Groq API fallback model: %s", config.GROQ_MODEL)
            response = self._groq_client.chat.completions.create(
                model=config.GROQ_MODEL,
                messages=[
                    {"role": "user", "content": prompt},
                ],
                temperature=config.LLM_TEMPERATURE,
                max_tokens=1024,
                timeout=config.GROQ_TIMEOUT,
            )
            if response.choices and len(response.choices) > 0:
                text = response.choices[0].message.content
                if text and text.strip():
                    return text.strip()
            logger.warning("Groq API returned an empty response")
            return None
        except Exception as exc:
            logger.error("Groq API fallback call failed: %s", exc)
            return None

    def _generate_once(self, model: str, prompt: str) -> str:
        attempt = 0
        while True:
            try:
                response = self._client.models.generate_content(
                    model=model,
                    contents=prompt,
                    config=self._gen_config,
                )
                text = self._extract_text(response)
                if not text or not text.strip():
                    raise LLMGenerationError("Model returned an empty response")
                return text.strip()
            except Exception as exc:  # noqa: BLE001 - classified below
                error = self._classify_error(exc)
                retryable = isinstance(error, (APIQuotaError, LLMTimeoutError))
                if retryable and attempt + 1 < config.LLM_MAX_RETRIES:
                    delay = config.LLM_RETRY_DELAY * (config.LLM_BACKOFF_FACTOR ** attempt)
                    logger.warning(
                        "Transient %s from %s; retrying in %.1fs",
                        type(error).__name__, model, delay,
                    )
                    time.sleep(delay)
                    attempt += 1
                    continue
                raise error

    # ------------------------------------------------------------------
    # Error handling
    # ------------------------------------------------------------------

    @staticmethod
    def _error_code(exc: Exception) -> Optional[int]:
        code = getattr(exc, "code", None)
        if isinstance(code, int):
            return code
        value = getattr(code, "value", None)
        if isinstance(value, int):
            return value
        return None

    @classmethod
    def _classify_error(cls, exc: Exception) -> LLMGenerationError:
        code = cls._error_code(exc)
        err_str = str(exc).lower()

        if code == 429 or "429" in err_str or "resource_exhausted" in err_str or "quota" in err_str:
            return APIQuotaError(str(exc))
        if code in (408, 504, 529):
            return LLMTimeoutError(str(exc))
        if any(
            phrase in err_str
            for phrase in (
                "deadline exceeded",
                "timed out",
                "timeout exceeded",
                "request timeout",
                "read timeout",
                "connect timeout",
                "connection timeout",
            )
        ):
            return LLMTimeoutError(str(exc))
        if (
            code in (403, 404, 401)
            or "permission_denied" in err_str
            or "not_found" in err_str
            or "no longer available" in err_str
            or "not found" in err_str
        ):
            unavailable = code == 404 or "no longer available" in err_str
            return APIAccessError(str(exc), unavailable=unavailable)
        return APIAccessError(str(exc), unavailable=False)

    @staticmethod
    def _status_for(error: Optional[Exception]) -> str:
        if isinstance(error, APIQuotaError):
            return LLMStatus.QUOTA
        if isinstance(error, LLMTimeoutError):
            return LLMStatus.TIMEOUT
        if isinstance(error, LLMGenerationError):
            return LLMStatus.GENERATION_ERROR
        return LLMStatus.API_ERROR

    @staticmethod
    def _extract_text(response: object) -> str:
        text = getattr(response, "text", None)
        if isinstance(text, str) and text.strip():
            return text

        parts: List[str] = []
        for candidate in getattr(response, "candidates", []) or []:
            content = getattr(candidate, "content", None)
            if content is None:
                continue
            for part in getattr(content, "parts", []) or []:
                part_text = getattr(part, "text", "")
                if part_text:
                    parts.append(part_text)
        return "".join(parts)

    # ------------------------------------------------------------------
    # Deterministic local fallback
    # ------------------------------------------------------------------

    def _fallback_generate(
        self,
        prompt: str,
        context_chunks: Optional[List[Tuple[str, Dict[str, object]]]] = None,
        conflicts: Optional[List[Dict[str, object]]] = None,
    ) -> str:
        chunks, question = self._prepare_chunks(prompt, context_chunks)
        if not chunks:
            return NOT_FOUND_ANSWER

        output: List[str] = []
        if conflicts:
            output.append(format_conflict_notice(conflicts))

        focused = focus_attributes(question)
        if focused:
            for attribute in focused:
                lines = self._extract_attribute(chunks, attribute)
                if lines:
                    output.extend(lines)
            if output:
                return "\n".join(output)

        return self._general_extract(chunks, question)

    def _prepare_chunks(
        self,
        prompt: str,
        context_chunks: Optional[List[Tuple[str, Dict[str, object]]]],
    ) -> Tuple[List[Tuple[str, Dict[str, object]]], str]:
        if context_chunks is not None:
            cleaned = [
                (content, metadata)
                for content, metadata in context_chunks
                if content and content.strip()
            ]
            return cleaned, self._extract_question(prompt)

        prefix = "Retrieved Context:\n"
        if prefix not in prompt:
            return [], ""
        rest = prompt.split(prefix, 1)[1]
        question = ""
        if "\n\nUser Question:\n" in rest:
            rest, question = rest.split("\n\nUser Question:\n", 1)

        chunks: List[Tuple[str, Dict[str, object]]] = []
        for block in re.split(r"\n\n---\n\n", rest):
            block = block.strip()
            if not block:
                continue
            metadata: Dict[str, object] = {}
            content_lines: List[str] = []
            for line in block.splitlines():
                stripped = line.strip()
                if stripped.startswith("Source:"):
                    metadata["source"] = stripped[len("Source:"):].strip()
                elif stripped.startswith("Page:"):
                    metadata["page"] = stripped[len("Page:"):].strip()
                elif stripped.startswith("Content Type:"):
                    metadata["content_type"] = stripped[len("Content Type:"):].strip()
                elif stripped.startswith("Document Type:"):
                    metadata["document_type"] = stripped[len("Document Type:"):].strip()
                elif stripped.startswith("Programme:"):
                    metadata["program_name"] = stripped[len("Programme:"):].strip()
                elif stripped.startswith(("Chunk ID:", "Score:")):
                    continue
                elif stripped.startswith("Content:"):
                    continue
                else:
                    content_lines.append(line)
            content = "\n".join(content_lines).strip()
            if content:
                chunks.append((content, metadata))
        return chunks, question.strip()

    @staticmethod
    def _extract_question(prompt: str) -> str:
        marker = "\n\nUser Question:\n"
        if marker in prompt:
            return prompt.split(marker, 1)[1].strip()
        return ""

    def _extract_attribute(
        self,
        chunks: List[Tuple[str, Dict[str, object]]],
        attribute: str,
    ) -> Optional[List[str]]:
        """Extract structured claims for one attribute from the evidence."""
        spec = config.ATTRIBUTE_TAXONOMY.get(attribute)
        if not spec:
            return None

        claims = []
        for content, metadata in chunks:
            for claim in extract_claims(content, metadata):
                if claim["attribute"] == attribute:
                    claims.append(claim)
        if not claims:
            return None

        label = spec.get("label", attribute)
        semantics = spec.get("semantics", "text")

        if semantics == "single":
            distinct = self._distinct_claim_groups(claims)
            if len(distinct) > 1:
                lines = [f'Note: The retrieved sources contain conflicting values for "{label}":']
                for claim in distinct:
                    lines.append(f"- {claim['value_text']} ({self._location(claim)})")
                return lines
            claim = claims[0]
            return [
                f"{label}: {claim['value_text']}",
                f"Source: {self._location(claim)}",
            ]

        if semantics == "set":
            seen = []
            for claim in claims:
                value = claim["value_text"]
                if value and not any(value == existing for existing in seen):
                    seen.append(value)
            if not seen:
                return None
            lines = [f"{label}:"]
            for value in seen[:12]:
                lines.append(f"- {value}")
            lines.append(f"Source: {self._location(claims[0])}")
            return lines

        claim = claims[0]
        return [
            f"{label}: {claim['value_text']}",
            f"Source: {self._location(claim)}",
        ]

    @staticmethod
    def _distinct_claim_groups(claims: List[Dict[str, object]]) -> List[Dict[str, object]]:
        groups = []
        for claim in claims:
            number = claim.get("number")
            if number is None:
                continue
            if any(abs(float(number) - float(group["number"])) < 1e-6 for group in groups):
                continue
            groups.append(claim)
        return groups

    @staticmethod
    def _location(claim: Dict[str, object]) -> str:
        source = str(claim.get("source") or "unknown")
        page = claim.get("page")
        if page is not None and str(page).strip() and str(page).lower() != "none":
            return f"{source}, page {page}"
        return source

    def _general_extract(
        self,
        chunks: List[Tuple[str, Dict[str, object]]],
        question: str,
    ) -> str:
        """Fallback keyword-based line extraction for non-attribute questions."""
        stop_words = {
            "what", "is", "the", "for", "and", "of", "in", "to", "a", "an",
            "about", "tell", "me", "how", "much", "does", "it", "are", "can",
            "do", "which", "where", "when", "why", "program", "programme",
        }
        tokens = [
            token for token in re.split(r"[^a-z0-9]+", question.lower())
            if len(token) > 1 and token not in stop_words
        ]
        if not tokens:
            return NOT_FOUND_ANSWER

        relevant: List[str] = []
        sources: List[str] = []
        for content, metadata in chunks:
            source = str(metadata.get("source") or "unknown")
            for line in content.splitlines():
                stripped = line.strip()
                if not stripped:
                    continue
                lowered = stripped.lower()
                if stripped.startswith("# ") and len(tokens) > 1:
                    continue
                if any(token in lowered for token in tokens):
                    relevant.append(stripped)
                    sources.append(source)

        if relevant:
            answer = "\n".join(relevant[:6])
            if len(answer) > 1400:
                answer = answer[:1400]
            return f"{answer}\n\nSource: {sources[0]}"

        # No token matched: fall back to a short excerpt of the top chunks.
        excerpt = []
        for content, _metadata in chunks:
            for line in content.splitlines():
                stripped = line.strip()
                if stripped and not stripped.startswith(("# ", "|")):
                    excerpt.append(stripped)
                if len(excerpt) >= 6:
                    break
            if len(excerpt) >= 6:
                break
        if excerpt:
            return f"{' '.join(excerpt)[:1400]}\n\nSource: {str(chunks[0][1].get('source') or 'unknown')}"
        return NOT_FOUND_ANSWER
